# Generated by Django 4.1 on 2022-09-05 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=128)),
                ('fecha_cracion', models.DateField(default=datetime.date.today)),
                ('fecha_entrega', models.DateField(default=datetime.date.today)),
                ('responsable', models.CharField(default='', max_length=128)),
                ('estado', models.CharField(default='PROGRESO', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=128)),
                ('apellido', models.CharField(default='', max_length=128)),
                ('codigo', models.CharField(default='', max_length=128)),
                ('contrasena', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
